SCR_EntityCatalogMultiList {
 m_aMultiLists {
  SCR_EntityCatalogMultiListEntry "{5CA0A9E60B892D2A}" {
   m_aEntities {
    SCR_EntityCatalogInventoryItem "{68C871D4782F8F62}" {
     m_sEntityPrefab "{6C15A3726729087D}Prefabs/Weapons/Explosives/M1A2_Bangalore/M1A2_Bangalore.et"
     m_aEntityDataList {
      SCR_ArsenalItem "{68C871D47594ECBD}" {
       m_eItemType EXPLOSIVES
       m_eRequiredRank SERGEANT
      }
     }
    }
   }
  }
 }
}